### ISSUE TITLE
Remove yaml, readonly & reload options

### ISSUE THREAD

**Issue by distantnative** [distantnative/field-multiselect#10]

**Comment by lukehatfield** [comment]
I was just making a [related articles section](https://getkirby.com/docs/solutions/blog/related-articles) on a new page. This multiselect option is perfect, but wish it could save in YAML syntax so I could use the [->pages](https://getkirby.com/docs/cheatsheet/field-methods/pages) method and get those pages easily on the front end. Did this used to be an option?

**Comment by distantnative** [comment]
Will think about it. Re-opening this one, so I won't forget about it.

**Comment by distantnative** [comment]
Moved it to its own new issue: #17
