### ISSUE TITLE
Option for YAML syntax

### ISSUE THREAD

**Issue by distantnative** [distantnative/field-multiselect#17]
**@lukehatfield wrote**

> I was just making a [related articles section](https://getkirby.com/docs/solutions/blog/related-articles) on a new page. This multiselect option is perfect, but wish it could save in YAML syntax so I could use the [`->pages`](https://getkirby.com/docs/cheatsheet/field-methods/pages) method and get those pages easily on the front end. Did this used to be an option?

**Comment by distantnative** [comment]
I might still consider an option, but for the meanwhile the `->pages()` method allows a parameter for non-YAML values to split the string along this parameter. So you should already be able to call it like this:

```php
<?php foreach($page->related()->pages(',') as $item): ?>
  …
<?php endforeach ?>
```

@lukehatfield

**Comment by lukehatfield** [comment]
I had no idea this could work. Perfect solution. Thank you!

**Comment by distantnative** [comment]
Just added it as a use case to the README and will be included in the new version today.
