### ISSUE TITLE
Debate on Principles: Panel Field as Plugin

### ISSUE THREAD

**Issue by dweidner** [distantnative/field-multiselect#18]
In the Kirby forum (https://forum.getkirby.com/t/multiselect-field/1213/19) you provided some reasoning why you implemented the field as plugin:

> It goes into site/plugins/field-multiselect/. The plugin then registers the field. With the new registry in Kirby 2.3, I believe all third-party elements like fields, snippets, blueprints etc. should also be delivered wrapped as a plugin. This enables us to keep only custom elements that are rather specific to the project in site/fields, site/tags etc.

I have to say, that I am not a fan of this movement even though I understand your idea. For me it would only make sense to use the new extension registry when the "plugin" would provide additional functionality like field- or page methods.

Will this be the general recommendation for Kirby Panel fields in the future?

**Comment by samnabi** [comment]
If it's literally just a field, I'm with @dweidner: the package belongs in `site/fields`.
This distinction between custom elements and third-party elements doesn't make sense to me, as I will probably re-use some of those "custom" elements in a future project.

**Comment by distantnative** [comment]
I gotta say that I completely understand that one can have different opinions about this. For me and some other developers, the distinction between custom/your own and third-party elements makes sense the most. And prefixing plugins according to their main component seems also pretty straightforward. So I am afraid we have to agree to disagree.

And this is no official Kirby recommendation, just my own personal decision how it works best for me. Of course I would advise others to do it this way. But simply for my personal point of view.
