### ISSUE TITLE
Error trying to install with Kirby CLI

### ISSUE THREAD

**Issue by malvese** [distantnative/field-multiselect#19]
When I try to install this plugin with the CLI (`kirby plugin:install distantnative/field-multiselect`) I get this error:

```
[RuntimeException]
Invalid Kirby Plugin Type
```

I have installed other plugins successfully, so I believe my configuration is correct.

**Comment by distantnative** [comment]
I'm a little confused here, though I can reproduce it. Seems to originate from these lines of the CLI: https://github.com/getkirby/cli/blob/master/src/PluginCommand.php#L90-L93

However, the package.json has set a `type`...

**Comment by malvese** [comment]
Ooo I had forgotten this issue. Turns out I had the exact same issue again with [another plugin](https://github.com/afbora/Kirby-Tabs-Field/issues/10) yesterday. Could it be a CLI bug? Plugins that are not fields install correctly.
I'll double check on a fresh install tomorrow.

**Comment by rasteiner** [comment]
Actually the error comes from invalid JSON (see that comma behind the "repository" object literal). PHP isn't able to parse the file, therefore the "field" property doesn't exist and therefore the CLI complains about it being "invalid". Just remove that comma, like [here](https://github.com/afbora/Kirby-Tabs-Field/pull/13) and it should work.

**Comment by schnti** [comment]
#20
