### ISSUE TITLE
Is there any way to change the separator?

### ISSUE THREAD

**Issue by saresq** [distantnative/field-multiselect#22]
Hi there im trying to show the multiselect as a text on HTML and i wanted to separate them with a `-` or even a ` ` blank space.

Is there any way of achieving this?

Thank you, and if i dont explain myself, please ask!

Thank you for your work

**Comment by distantnative** [comment]
I assume you could simply use `str_replace` to turn all `,` into your desired character: http://php.net/manual/de/function.str-replace.php

**Comment by saresq** [comment]
Im trying this and wont work, know why?

                  `<?= str_replace(",", "",$section->multiselect()); ?>`

**Comment by saresq** [comment]
Cool Str_replace worked like a charm!
