### ISSUE TITLE
Add ability for user to add their own option

### ISSUE THREAD

**Issue by fitzage** [distantnative/field-multiselect#28]
I want to fill this via json from a list of tags generated by a template elsewhere. I want the ability for a user to add their own item to the list that will then be saved when the file is saved, which will then update the json file, which will then make it available on other pages as well.

Does that make sense? Now that I talk it out like that, it sounds like it might be a bit more complicated than I initially thought, but that's my feature request.

**Comment by distantnative** [comment]
Finally possible via Kirby 3
